name: Django CI

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Migrations
        run: |
          cd backend
          python manage.py migrate

      - name: Run Tests
        run: |
          cd backend
          python manage.py test